import { auth } from "./lib/auth";
import { headers } from "next/headers";
import { serializeSignedCookie } from "better-call";

async function test() {
  try {
    const secret = process.env.BETTER_AUTH_SECRET!;
    const users = await auth.$context.then(ctx => ctx.internalAdapter.listUsers());
    if (users.length === 0) {
      console.log("No users.");
      return;
    }
    const user = users[0];
    
    // Create session via adapter
    const ctx = await auth.$context;
    const session = await ctx.internalAdapter.createSession(user.id);
    console.log("Created session:", session);

    // Use setSessionCookie from better-auth/cookies
    const { setSessionCookie } = require("better-auth/cookies");
    
    // We need a mock request/response context if setSessionCookie requires it
    // Wait, let's just see if auth.api.getSession works if we use the exact cookie header generated by setSessionCookie
    // But how do we capture the cookie header? setSessionCookie modifies ctx.responseHeaders
    
    // Actually, we can use createCookieGetter or just rely on the API!
    console.log("We can use setSessionCookie!");
    
    // If failed, let's try signing it with ctx.secret
    if (!fetchedSession) {
      console.log("Trying with ctx.secret...");
      const signed2 = await serializeSignedCookie("better-auth.session_token", session.token, ctx.secret);
      const mockHeaders2 = new Headers();
      mockHeaders2.append("Cookie", `better-auth.session_token=${signed2}`);
      const fetched2 = await auth.api.getSession({ headers: mockHeaders2 });
      console.log("Fetched with ctx.secret:", fetched2 ? "SUCCESS" : "FAILED");
    }

  } catch (e) {
    console.error(e);
  }
}
test();
